/* generated by tools/xlsx_to_data.py - do not edit by hand */
window.SLD_INVERTERS = [
 {
  "brand": "KACO",
  "model": "blueplanet 125 NX3 M10",
  "current": 182,
  "ac": "120mm2/4C/Al/XLPE/PVC",
  "earth": "35mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "KACO",
  "model": "blueplanet 100 NX3 M8",
  "current": 182,
  "ac": "120mm2/4C/Al/XLPE/PVC",
  "earth": "25mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "KACO",
  "model": "blueplanet 60 NX3 M5",
  "current": 95.3,
  "ac": "50mm2/4C/Al/XLPE/PVC",
  "earth": "16mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "KACO",
  "model": "blueplanet 50 NX3 M5",
  "current": 83.6,
  "ac": "35mm2/4C/Al/XLPE/PVC",
  "earth": "16mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "KACO",
  "model": "blueplanet 20.0 NX3 M2",
  "current": 31.9,
  "ac": "10mm2/4C/Cu/PVC/PVC",
  "earth": "6mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "KACO",
  "model": "blueplanet 15.0 NX3 M2",
  "current": 24,
  "ac": "6mm2/4C/Cu/PVC/PVC",
  "earth": "6mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "KACO",
  "model": "blueplanet 10.0 NX3 M2",
  "current": 16,
  "ac": "6mm2/4C/Cu/PVC/PVC",
  "earth": "6mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Sunways",
  "model": "STT-150KTL-SE",
  "current": 250,
  "ac": "150mm2/4C/Al/XLPE/PVC",
  "earth": "50mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Sunways",
  "model": "STT-136KTL-SE",
  "current": 226.7,
  "ac": "150mm2/4C/Al/XLPE/PVC",
  "earth": "50mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Sunways",
  "model": "STT-125KTL-SE",
  "current": 206.1,
  "ac": "120mm2/4C/Al/XLPE/PVC",
  "earth": "35mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Sunways",
  "model": "STT-110KTL-SE",
  "current": 183.3,
  "ac": "120mm2/4C/Al/XLPE/PVC",
  "earth": "25mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Sunways",
  "model": "STT-100KTL-SE",
  "current": 166.7,
  "ac": "95mm2/4C/Al/XLPE/PVC",
  "earth": "25mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Sunways",
  "model": "STT-80KTL",
  "current": 127,
  "ac": "70mm2/4C/AL/XLPE/PVC",
  "earth": "16mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Sunways",
  "model": "STT-60KTL-P",
  "current": 95.3,
  "ac": "50mm2/4C/Al/XLPE/PVC",
  "earth": "16mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Sunways",
  "model": "STT-50KTL-P",
  "current": 83.6,
  "ac": "35mm2/4C/Al/XLPE/PVC",
  "earth": "16mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Sunways",
  "model": "STT-60KTL-M",
  "current": 95.7,
  "ac": "50mm2/4C/Al/XLPE/PVC",
  "earth": "16mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Sunways",
  "model": "STT-50KTL-M",
  "current": 79.7,
  "ac": "35mm2/4C/Al/XLPE/PVC",
  "earth": "16mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Sunways",
  "model": "STT-45KTL",
  "current": 71.7,
  "ac": "35mm2/4C/Al/XLPE/PVC",
  "earth": "16mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Sunways",
  "model": "STT-40KTL",
  "current": 63.8,
  "ac": "25mm2/4C/Al/PVC/PVC",
  "earth": "10mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Sunways",
  "model": "STT-36KTL",
  "current": 57.4,
  "ac": "16mm2/4C/Cu/PVC/PVC",
  "earth": "10mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Sunways",
  "model": "STT-33KTL",
  "current": 52.6,
  "ac": "16mm2/4C/Cu/PVC/PVC",
  "earth": "10mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Sunways",
  "model": "STT-30KTL",
  "current": 47.8,
  "ac": "16mm2/4C/Cu/PVC/PVC",
  "earth": "10mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Sunways",
  "model": "STT-29.9KTL",
  "current": 43.3,
  "ac": "16mm2/4C/Cu/PVC/PVC",
  "earth": "10mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Sunways",
  "model": "STT-25KTL-P",
  "current": 39,
  "ac": "16mm2/4C/Cu/PVC/PVC",
  "earth": "10mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Sunways",
  "model": "STT-20KTL-P",
  "current": 31.9,
  "ac": "10mm2/4C/Cu/PVC/PVC",
  "earth": "6mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Sunways",
  "model": "STT-17KTL-P",
  "current": 28.4,
  "ac": "6mm2/4C/Cu/PVC/PVC",
  "earth": "6mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Sunways",
  "model": "STT-15KTL-P",
  "current": 25,
  "ac": "6mm2/4C/Cu/PVC/PVC",
  "earth": "6mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Sunways",
  "model": "STT-12KTL-P",
  "current": 20,
  "ac": "6mm2/4C/Cu/PVC/PVC",
  "earth": "6mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Sunways",
  "model": "STT-10KTL-P",
  "current": 16.5,
  "ac": "6mm2/4C/Cu/PVC/PVC",
  "earth": "6mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Huawei",
  "model": "Sun2000-150K-MG0",
  "current": 240.5,
  "ac": "240mm2/4C/Al/XLPE/PVC",
  "earth": "50mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Huawei",
  "model": "Sun2000-115KTL-M2",
  "current": 182.3,
  "ac": "120mm2/4C/Al/XLPE/PVC",
  "earth": "35mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Huawei",
  "model": "Sun2000-100KTL-M2",
  "current": 160.4,
  "ac": "120mm2/4C/Al/XLPE/PVC",
  "earth": "25mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Huawei",
  "model": "Sun2000-50KTL-M3",
  "current": 79.8,
  "ac": "35mm2/4C/Al/XLPE/PVC",
  "earth": "16mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Huawei",
  "model": "Sun2000-40KTL-M3",
  "current": 63.8,
  "ac": "25mm2/4C/Al/PVC/PVC",
  "earth": "10mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Huawei",
  "model": "Sun2000-36KTL-M3",
  "current": 58,
  "ac": "16mm2/4C/Cu/PVC/PVC",
  "earth": "10mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Huawei",
  "model": "Sun2000-30KTL-M3",
  "current": 47.9,
  "ac": "16mm2/4C/Cu/PVC/PVC",
  "earth": "10mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Huawei",
  "model": "Sun2000-25KTL-M5",
  "current": 39.9,
  "ac": "16mm2/4C/Cu/PVC/PVC",
  "earth": "10mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Huawei",
  "model": "Sun2000-20KTL-M5",
  "current": 31.9,
  "ac": "10mm2/4C/Cu/PVC/PVC",
  "earth": "6mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Huawei",
  "model": "Sun2000-17KTL-M5",
  "current": 27.1,
  "ac": "6mm2/4C/Cu/PVC/PVC",
  "earth": "6mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Huawei",
  "model": "Sun2000-15KTL-M5",
  "current": 23.9,
  "ac": "6mm2/4C/Cu/PVC/PVC",
  "earth": "6mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Huawei",
  "model": "Sun2000-12KTL-M5",
  "current": 17.3,
  "ac": "6mm2/4C/Cu/PVC/PVC",
  "earth": "6mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Huawei",
  "model": "Sun2000-10KTL-M1",
  "current": 15,
  "ac": "6mm2/4C/Cu/PVC/PVC",
  "earth": "6mm2 Cu/ PVc Earth Cable",
  "type": "string"
 },
 {
  "brand": "Huawei",
  "model": "Sungrow-SG150CX",
  "current": 240.6,
  "ac": null,
  "earth": null,
  "type": "string"
 },
 {
  "brand": "Huawei",
  "model": "Sungrow-SG125CX-P2",
  "current": 189.9,
  "ac": null,
  "earth": null,
  "type": "string"
 },
 {
  "brand": "Huawei",
  "model": "Sungrow-SG125CX-P3",
  "current": 181.1,
  "ac": null,
  "earth": null,
  "type": "string"
 },
 {
  "brand": "Sunways Hybrid",
  "model": "STH-33KTL-HT",
  "current": 55,
  "ac": "16mm2/4C/Cu/PVC/PVC",
  "earth": null,
  "type": "hybrid"
 },
 {
  "brand": "Sunways Hybrid",
  "model": "STH-30KTL-HT",
  "current": 50,
  "ac": "16mm2/4C/Cu/PVC/PVC",
  "earth": null,
  "type": "hybrid"
 },
 {
  "brand": "Sunways Hybrid",
  "model": "STH-25KTL-HT",
  "current": 41.7,
  "ac": "16mm2/4C/Cu/PVC/PVC",
  "earth": null,
  "type": "hybrid"
 },
 {
  "brand": "Sunways Hybrid",
  "model": "STH-20KTL-HT",
  "current": 33.3,
  "ac": "10mm2/4C/Cu/PVC/PVC",
  "earth": null,
  "type": "hybrid"
 },
 {
  "brand": "Sunways Hybrid",
  "model": "STH-17KTL-HT",
  "current": 28.3,
  "ac": "6mm2/4C/Cu/PVC/PVC",
  "earth": null,
  "type": "hybrid"
 },
 {
  "brand": "Sunways Hybrid",
  "model": "STH-15KTL-HT",
  "current": 25,
  "ac": "6mm2/4C/Cu/PVC/PVC",
  "earth": null,
  "type": "hybrid"
 },
 {
  "brand": "Sunways Hybrid",
  "model": "STH-12KTL-HTP",
  "current": 20,
  "ac": "6mm2/4C/Cu/PVC/PVC",
  "earth": null,
  "type": "hybrid"
 },
 {
  "brand": "Sunways Hybrid",
  "model": "STH-10KTL-HTP",
  "current": 16.5,
  "ac": "6mm2/4C/Cu/PVC/PVC",
  "earth": null,
  "type": "hybrid"
 },
 {
  "brand": "ATESS Hybrid",
  "model": "HPS-125KTL",
  "current": 181,
  "ac": "120mm2/4C/Al/XLPE/PVC",
  "earth": null,
  "type": "hybrid"
 },
 {
  "brand": "ATESS Hybrid",
  "model": "HPS-100KTL",
  "current": 144,
  "ac": "120mm2/4C/Al/XLPE/PVC",
  "earth": null,
  "type": "hybrid"
 },
 {
  "brand": "ATESS Hybrid",
  "model": "HPS-150HV",
  "current": 217,
  "ac": "240mm2/4C/Al/XLPE/PVC",
  "earth": null,
  "type": "hybrid"
 },
 {
  "brand": "ATESS Hybrid",
  "model": "HPS-100HV",
  "current": 144,
  "ac": "120mm2/4C/Al/XLPE/PVC",
  "earth": null,
  "type": "hybrid"
 },
 {
  "brand": "ATESS Hybrid",
  "model": "HPS-150",
  "current": 217,
  "ac": "240mm2/4C/Al/XLPE/PVC",
  "earth": null,
  "type": "hybrid"
 },
 {
  "brand": "ATESS Hybrid",
  "model": "HPS-120",
  "current": 173,
  "ac": "120mm2/4C/Al/XLPE/PVC",
  "earth": null,
  "type": "hybrid"
 },
 {
  "brand": "ATESS Hybrid",
  "model": "HPS-100",
  "current": 144,
  "ac": "120mm2/4C/Al/XLPE/PVC",
  "earth": null,
  "type": "hybrid"
 },
 {
  "brand": "ATESS Hybrid",
  "model": "HPS-50",
  "current": 72,
  "ac": "35mm2/4C/Al/XLPE/PVC",
  "earth": null,
  "type": "hybrid"
 },
 {
  "brand": "ATESS Hybrid",
  "model": "HPS-30",
  "current": 43,
  "ac": "16mm2/4C/Cu/PVC/PVC",
  "earth": null,
  "type": "hybrid"
 },
 {
  "brand": "ATESS Hybrid",
  "model": "HPS-50KTL",
  "current": 72,
  "ac": "35mm2/4C/Al/XLPE/PVC",
  "earth": null,
  "type": "hybrid"
 },
 {
  "brand": "ATESS Hybrid",
  "model": "HPS-40KTL",
  "current": 57,
  "ac": "25mm2/4C/Al/PVC/PVC",
  "earth": null,
  "type": "hybrid"
 },
 {
  "brand": "ATESS Hybrid",
  "model": "HPS-30KTL",
  "current": 43,
  "ac": "16mm2/4C/Cu/PVC/PVC",
  "earth": null,
  "type": "hybrid"
 },
 {
  "brand": "ATESS Hybrid",
  "model": "HPS-20KTL",
  "current": 28,
  "ac": "10mm2/4C/Cu/PVC/PVC",
  "earth": null,
  "type": "hybrid"
 },
 {
  "brand": "ATESS Hybrid",
  "model": "HPS-15KTL",
  "current": 21,
  "ac": "6mm2/4C/Cu/PVC/PVC",
  "earth": null,
  "type": "hybrid"
 }
];
