"""Embed assets/regen-logo.png into js/logo.js (data URI) so downloaded SVGs are self-contained.
Usage: pip install pillow && python tools/logo_to_js.py [logo.png]"""
import base64, io, sys
from PIL import Image
im = Image.open(sys.argv[1] if len(sys.argv) > 1 else 'assets/regen-logo.png').convert('RGBA')
im.thumbnail((360, 360))
buf = io.BytesIO(); im.save(buf, 'PNG', optimize=True)
open('js/logo.js', 'w').write('/* generated by tools/logo_to_js.py */\nwindow.SLD_LOGO = "data:image/png;base64,' + base64.b64encode(buf.getvalue()).decode() + '";\n')
print(im.size, len(buf.getvalue()), 'bytes')
