"""Rebuild js/inverter-data.js from data/Supporting_file.xlsx.
Usage:  pip install openpyxl && python tools/xlsx_to_data.py
Columns (from C): Brand | Inverter | Current (A) | AC cable | Inverter earth
Brand is filled down; duplicate model names are skipped (first one wins);
empty cable/earth cells stay null and the app derives them from the current."""
import json, re, sys, openpyxl
src = sys.argv[1] if len(sys.argv) > 1 else 'data/Supporting_file.xlsx'
ws = openpyxl.load_workbook(src, data_only=True).active
clean = lambda s: re.sub(r'^\s*[\d.]+\s*\(|\)\s*$', '', str(s)).strip() if s else None
out, seen, brand, skipped = [], set(), '', 0
for b, m, cur, ac, ea in ws.iter_rows(min_col=3, max_col=7, values_only=True):
    if b: brand = str(b).strip()
    if not m or m == 'Inverters' or not isinstance(cur, (int, float)): continue
    model = clean(m)
    if model in seen: skipped += 1; continue
    seen.add(model)
    out.append(dict(brand=brand, model=model, current=cur, ac=clean(ac),
                    earth=str(ea).strip() if ea else None,
                    type='hybrid' if 'Hybrid' in brand else 'string'))
open('js/inverter-data.js', 'w', encoding='utf-8').write(
    '/* generated by tools/xlsx_to_data.py - do not edit by hand */\nwindow.SLD_INVERTERS = ' + json.dumps(out, ensure_ascii=False, indent=1) + ';\n')
print(len(out), 'inverters written,', skipped, 'duplicate rows skipped')
